# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testupload', '0002_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='updatee_date',
            new_name='updated_date',
        ),
    ]
