# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testupload', '0003_auto_20160315_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
