# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testupload', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
