# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-22 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='list', to='testmodelform.Author'),
        ),
    ]
