# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-22 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodelform', '0002_auto_20160322_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
