# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name="'Person's first name")),
                ('last_name', models.CharField(max_length=30, verbose_name="'Person's last name")),
            ],
        ),
    ]
